use std::fmt::{Display, Formatter};
use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::{PluginError, PluginResult};

/// Stable plugin API level supported by the host and SDK.
pub const SUPPORTED_PLUGIN_API: u32 = 1;

/// Canonical capability model used by the SDK and manifest generation.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "lowercase")]
pub enum Capability {
    Network,
    Config,
    Cache,
    Filesystem,
}

impl Display for Capability {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Capability {
    /// Stable string representation used in metadata and manifests.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Network => "network",
            Self::Config => "config",
            Self::Cache => "cache",
            Self::Filesystem => "filesystem",
        }
    }
}

/// Public compatibility guarantees exposed by the SDK.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CompatibilityPolicy {
    pub plugin_api: u32,
    pub stable_surface: &'static [&'static str],
    pub breaking_change_rules: &'static [&'static str],
}

impl CompatibilityPolicy {
    /// Current SDK compatibility policy.
    pub fn current() -> Self {
        Self {
            plugin_api: SUPPORTED_PLUGIN_API,
            stable_surface: &[
                "Plugin metadata JSON schema emitted by --metadata",
                "Manifest schema generated by PluginManifest",
                "Context typed config accessors and capability helpers",
                "Command routing contract and output primitives",
            ],
            breaking_change_rules: &[
                "Changes to plugin_api require a major host and SDK transition",
                "Removing public SDK types or methods requires a new SDK major version",
                "Manifest field additions must be backward compatible by default",
            ],
        }
    }
}

/// Metadata JSON exposed to the host via `--metadata`.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct PluginMetadata {
    pub name: String,
    pub version: String,
    pub description: String,
    #[serde(default)]
    pub author: Option<String>,
    #[serde(default)]
    pub commands: Vec<String>,
    pub compatibility: PluginCompatibility,
    #[serde(default)]
    pub capabilities: Vec<Capability>,
    pub api_version: u32,
    pub plugin_api: u32,
}

impl PluginMetadata {
    pub fn new(
        name: impl Into<String>,
        version: impl Into<String>,
        compatibility_policy: CompatibilityPolicy,
    ) -> Self {
        let name = name.into();
        Self {
            name: name.clone(),
            version: version.into(),
            description: String::new(),
            author: None,
            commands: vec![name],
            compatibility: PluginCompatibility {
                tinfo: ">=0.9.0".to_string(),
                plugin_api: compatibility_policy.plugin_api,
            },
            capabilities: Vec::new(),
            api_version: compatibility_policy.plugin_api,
            plugin_api: compatibility_policy.plugin_api,
        }
    }

    pub fn push_capability(&mut self, capability: Capability) {
        if !self.capabilities.contains(&capability) {
            self.capabilities.push(capability);
            self.capabilities.sort();
        }
    }

    pub fn push_command(&mut self, command: impl Into<String>) {
        let command = command.into();
        if !self.commands.contains(&command) {
            self.commands.push(command);
            self.commands.sort();
        }
    }

    /// Validate metadata for SDK-level correctness.
    pub fn validate(&self) -> ManifestValidation {
        let mut issues = Vec::new();
        if self.name.trim().is_empty() {
            issues.push("metadata.name must not be empty".to_string());
        }
        if self.version.trim().is_empty() {
            issues.push("metadata.version must not be empty".to_string());
        }
        if self.description.trim().is_empty() {
            issues.push("metadata.description must not be empty".to_string());
        }
        if self.commands.is_empty() {
            issues
                .push("metadata.commands must include at least one top-level command".to_string());
        }
        if self.plugin_api != SUPPORTED_PLUGIN_API || self.api_version != SUPPORTED_PLUGIN_API {
            issues.push(format!(
                "metadata.plugin_api and metadata.api_version must be {SUPPORTED_PLUGIN_API}"
            ));
        }
        ManifestValidation { issues }
    }
}

/// Compatibility metadata shared by the SDK and host.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct PluginCompatibility {
    pub tinfo: String,
    pub plugin_api: u32,
}

/// Manifest model owned by the SDK.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct PluginManifest {
    pub plugin: PluginSection,
    pub command: CommandSection,
    pub compatibility: CompatibilitySection,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requirements: Option<RequirementsSection>,
}

impl PluginManifest {
    pub fn from_metadata(metadata: &PluginMetadata) -> Self {
        Self {
            plugin: PluginSection {
                name: metadata.name.clone(),
                version: metadata.version.clone(),
                description: metadata.description.clone(),
                author: metadata.author.clone(),
            },
            command: CommandSection {
                name: metadata.name.clone(),
            },
            compatibility: CompatibilitySection {
                terminal_info: metadata.compatibility.tinfo.clone(),
                plugin_api: metadata.plugin_api,
            },
            requirements: if metadata.capabilities.is_empty() {
                None
            } else {
                Some(RequirementsSection {
                    capabilities: metadata
                        .capabilities
                        .iter()
                        .map(ToString::to_string)
                        .collect(),
                })
            },
        }
    }

    pub fn validate(&self) -> ManifestValidation {
        let mut issues = Vec::new();
        if self.plugin.name.trim().is_empty() {
            issues.push("plugin.name must not be empty".to_string());
        }
        if self.plugin.version.trim().is_empty() {
            issues.push("plugin.version must not be empty".to_string());
        }
        if self.plugin.description.trim().is_empty() {
            issues.push("plugin.description must not be empty".to_string());
        }
        if self.command.name.trim().is_empty() {
            issues.push("command.name must not be empty".to_string());
        }
        if self.compatibility.plugin_api != SUPPORTED_PLUGIN_API {
            issues.push(format!(
                "compatibility.plugin_api must be {SUPPORTED_PLUGIN_API}"
            ));
        }
        ManifestValidation { issues }
    }

    pub fn to_toml_string(&self) -> PluginResult<String> {
        let validation = self.validate();
        validation.into_result()?;
        Ok(format!("{}\n", toml::to_string_pretty(self)?))
    }

    pub fn write_to_path(&self, path: impl AsRef<Path>) -> PluginResult<()> {
        fs::write(path, self.to_toml_string()?).map_err(PluginError::from)
    }

    pub fn read_from_path(path: impl AsRef<Path>) -> PluginResult<Self> {
        let contents = fs::read_to_string(path)?;
        let manifest = toml::from_str::<Self>(&contents)?;
        manifest.validate().into_result()?;
        Ok(manifest)
    }
}

/// Result of manifest validation.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ManifestValidation {
    pub issues: Vec<String>,
}

impl ManifestValidation {
    pub fn is_valid(&self) -> bool {
        self.issues.is_empty()
    }

    pub fn into_result(self) -> PluginResult<()> {
        if self.issues.is_empty() {
            Ok(())
        } else {
            Err(PluginError::new(self.issues.join("; ")))
        }
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct PluginSection {
    pub name: String,
    pub version: String,
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommandSection {
    pub name: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct CompatibilitySection {
    pub terminal_info: String,
    pub plugin_api: u32,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub struct RequirementsSection {
    pub capabilities: Vec<String>,
}
